version: '3.4'

services:
  server:
    image: ${DOCKER_REGISTRY-}server
    build:
      context: .
      dockerfile: Server/Dockerfile
    depends_on:
      -  postgres
    networks:
      -  server-db-network

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    networks:
      -  server-db-network
  
  client:
    image: ${DOCKER_REGISTRY-}client
    build:
      context: ./Client
      dockerfile: ./Dockerfile
    depends_on:
      -  server

networks:
  server-db-network:
    driver: bridge