version: '3.4'

services:
  server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "40005:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  client:
    ports:
      - '3001:3000'
    #environment:
    #  - NODE_ENV=development
    volumes:
      - './Client:/app'
      - '/app/node_modules'